apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customclusterbuilders.experimental.kpack.pivotal.io
spec:
  group: experimental.kpack.pivotal.io
  version: v1alpha1
  names:
    kind: CustomClusterBuilder
    singular: customclusterbuilder
    plural: customclusterbuilders
    shortNames:
    - ccb
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}